package ModeloControlador;

public enum posiblesCambios {
	CANTIDAD_JUGADORES_ERRONEA, 
	NUEVAS_CARTAS_JUGADORES, 
	NUEVO_JUGADOR, 
	ESTADO_JUEGO, 
	NUEVA_CARTA_DESCARTADA, 
	NUEVO_TURNO_JUGADOR, 
	VERIFICAR_TODOS_LISTOS, 
	JUEGO_NO_CONFIGURADO, 
	LEVANTA_CARTA, 
	MOSTRAR_2_CARTAS_JUGADORES, 
	JUEGO_TERMINADO, 
	UN_JUGADOR_DIJO_CUBO, 
	ERROR, MANO_TERMINADA, 
	ACTUALIZAR_LISTA_JUGADORES, FIN_TURNO_HABILITADO, VERIFICAR_VIO_CARTA, COMENZO_EL_JUEGO, PUEDE_VER_CARTA, PUEDE_INTERCAMBIAR_CARTA,
	NUEVAS_CARTAS_JUGADOR_A_MOSTRAR_CARTA,
	
}
