package ModeloControlador;

public enum posiblesCambios {
	NUEVAS_CARTAS_JUGADORES, 
	ESTADO_JUEGO, 
	NUEVA_CARTA_DESCARTADA, 
	NUEVO_TURNO_JUGADOR, 
	JUEGO_TERMINADO, 
	UN_JUGADOR_DIJO_CUBO, 
	ERROR,
	ACTUALIZAR_LISTA_JUGADORES,
	PUEDE_VER_CARTA,
	PUEDE_INTERCAMBIAR_CARTA,
	NUEVAS_CARTAS_JUGADOR_A_MOSTRAR_CARTA,
	CARGANDO_JUEGO,
	COMENZO_JUEGO,
	
}
