package Modelo;

public enum estadoJuego {
	JUGANDO,
	JUGABLE,
	CONFIGURANDO,
	INICIAL,
	TERMINADO, MANO_TERMINADA, MOSTRANDO_CARTAS_INICIALES,MOSTRANDO_CARTA, MOSTRANDO_CARTA_MAZO, INTERCAMBIANDO_CARTAS,
}
